name: Earlyrain Studio
favicon: null
layout_spectrum: 0.8902
typography_spectrum: 0.31566
title: Earlyrain Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6aace0'
    - '#b0d6ed'
    - '#323754'
    - '#baa496'
    - '#6f665f'
  brandStrength: 0.6875
  lightness: 0.22598154400475323
  saturation: 0.19086626591160893
  rhythmicContrast: 0.5917643113061786
purpose: []
