name: Earlyrain Studio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5416281735524535
title: Earlyrain Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#67aeec'
    - '#4287d2'
    - '#b6ceea'
    - '#43512e'
  brandStrength: 0.5625
  lightness: 0.22598154400475323
  saturation: 0.19086626591160893
  rhythmicContrast: 0.5917643113061786
purpose: []
