name: Earlyrain Studio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19922
title: Earlyrain Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#007dfe'
    - '#fefefe'
    - '#5f5800'
    - '#6cb1fa'
    - '#baa900'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
